# Generated by Django 6.0.2 on 2026-02-24 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_info',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits'), django.core.validators.MaxLengthValidator(10, message='Phone number must be exactly 10 digits'), django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits(number only)', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
