# Generated by Django 6.0.2 on 2026-02-25 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_contact_info_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact_info',
            new_name='primary_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits'), django.core.validators.MaxLengthValidator(10, message='Phone number must be exactly 10 digits'), django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits(number only)', regex='^\\d{10}$')]),
        ),
    ]
