# Generated by Django 6.0.2 on 2026-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='section',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'section')},
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
