# Generated by Django 6.0.2 on 2026-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_remove_studentclass_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
