# Generated by Django 6.0.2 on 2026-02-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_class_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='grade.class')),
            ],
            options={
                'unique_together': {('name', 'class_group')},
            },
        ),
    ]
