# Generated by Django 6.0.2 on 2026-02-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_alter_class_section_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
    ]
