# Generated by Django 6.0.2 on 2026-02-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_alter_class_unique_together_remove_class_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['order'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='display_name',
        ),
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
