# Generated by Django 6.0.2 on 2026-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_alter_class_options_remove_class_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.CharField(default='Nikeshh', max_length=50),
        ),
    ]
