# Generated by Django 6.0.2 on 2026-03-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_class_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.CharField(blank=True, default='Nikeshh', max_length=50),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('subject_code', models.CharField(max_length=20)),
                ('teacher', models.CharField(blank=True, default='Demo Teacher', max_length=50)),
                ('of_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='grade.class')),
            ],
        ),
    ]
